### PR TITLE
solution

### PR DESCRIPTION
**Pull request by ShamievDavid**
[DEMO LINK](https:/ShamievDavid.github.io/react_keyboard/)

### CODE REVIEW

**Review by mykhalenych — CHANGES_REQUESTED** [review]
your demo link isn't working

**Review by OleziO — COMMENTED** [review]
Open your PR.

**Comment by ShamievDavid** [comment]
✨

**Comment by ShamievDavid** [comment]
***

**Comment by ShamievDavid** [comment]
gsefe

**Comment by ShamievDavid** [comment]
vdss

**Comment by ShamievDavid** [comment]
?

**Comment by ShamievDavid** [comment]
ff

**Pull request closed without merging**
