### PR TITLE
complete the task

### PR DESCRIPTION
**Pull request by barsuchellos**

### CODE REVIEW

**Review by jojnajbude — APPROVED** [review]
Add link to demo,pls. not bad at all.

**Comment by barsuchellos** [comment]
> Add link to demo,pls. not bad at all.

**Comment by barsuchellos** [comment]
> y, my bad)

**Comment by barsuchellos** [comment]
> _ No description provided. _

[DEMO LINK](https://barsuchellos.github.io/react_keyboard/)

**Review by Denchepornyuk — APPROVED** [review]

**Pull request closed without merging**
